#! /bin/sh

#	================================================
#
#	██████╗░░██████╗██████╗░░██╗░░░░░░░██╗███╗░░░███╗
#	██╔══██╗██╔════╝██╔══██╗░██║░░██╗░░██║████╗░████║
#	██████╦╝╚█████╗░██████╔╝░╚██╗████╗██╔╝██╔████╔██║
#	██╔══██╗░╚═══██╗██╔═══╝░░░████╔═████║░██║╚██╔╝██║
#	██████╦╝██████╔╝██║░░░░░░░╚██╔╝░╚██╔╝░██║░╚═╝░██║
#	╚═════╝░╚═════╝░╚═╝░░░░░░░░╚═╝░░░╚═╝░░╚═╝░░░░░╚═╝
#
#	=================================================

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
dunst &
xrandr --rate 120 &
feh --bg-fill --randomize ~/Pictures/Art/* &
#feh --bg-fill --randomize ~/Pictures/Art/1594677265609.jpg &
~/.config/myscripts/polybar/launch.sh &
~/.config/myscripts/low_bat_notifier.sh &

# Workspaces

# Roman
#bspc monitor -d α β γ δ ε
bspc monitor -d α β γ δ ε ζ η θ ι κ

# Numbers
#bspc monitor -d I II III IV V VI VII VIII IX X

# Other stuff
bspc config border_width         	2
bspc config window_gap          	5

bspc config split_ratio          	0.5
bspc config single_monocle		true
bspc config focus_follows_pointer	false
bspc config borderless_monocle  	true
bspc config gapless_monocle      	true

# Color stuff
bspc config focused_border_color	"#FABD2F"
